name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan

      - name: Convert Plan to JSON
        run: terraform show -json plan.tfplan > plan.json

      - name: Run tfplan2md
        run: |
          docker run -v ${{ github.workspace }}:/data oocx/tfplan2md /data/plan.json > plan.md

      - name: Upload Plan Report
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-report
          path: plan.md
